version: "0.1"

services:
  db:
    image: mysql:8.3
    container_name: database
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d

  backend:
    build: ../nursing-home-server/server
    container_name: backend
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: ${MYSQL_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db

  frontend:
    build: ../nursing-home
    container_name: frontend
    restart: always
    ports:
      - 80:3000
    command: node server.js
